import { User, Application } from '@/types';

export const DEMO_USER: User = {
  id: '1',
  firstName: 'John',
  lastName: 'Doe',
  email: 'demo@applyflow.com',
  phone: '+1-555-0123',
  university: 'MIT',
  linkedin: 'https://linkedin.com/in/johndoe',
  portfolio: 'https://johndoe.dev',
  role: 'user',
  createdAt: new Date(2024, 0, 1).toISOString(),
};

export const ADMIN_USER: User = {
  id: '2',
  firstName: 'Admin',
  lastName: 'User',
  email: 'admin@applyflow.com',
  phone: '+1-555-0124',
  university: 'Stanford',
  linkedin: 'https://linkedin.com/in/adminuser',
  portfolio: 'https://admin.dev',
  role: 'admin',
  createdAt: new Date(2024, 0, 1).toISOString(),
};

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: '1',
    userId: '1',
    company: 'Google',
    position: 'Senior Software Engineer',
    url: 'https://careers.google.com/jobs/1',
    dateApplied: new Date(2024, 3, 15).toISOString(),
    note: 'Applied through referral from John',
    status: 'Interview',
    priority: 'high',
    createdAt: new Date(2024, 3, 15).toISOString(),
    updatedAt: new Date(2024, 3, 20).toISOString(),
  },
  {
    id: '2',
    userId: '1',
    company: 'Meta',
    position: 'Software Engineer - Backend',
    url: 'https://careers.meta.com/jobs/2',
    dateApplied: new Date(2024, 3, 10).toISOString(),
    note: 'Great opportunity',
    status: 'Pending',
    priority: 'medium',
    createdAt: new Date(2024, 3, 10).toISOString(),
    updatedAt: new Date(2024, 3, 18).toISOString(),
  },
  {
    id: '3',
    userId: '1',
    company: 'Apple',
    position: 'iOS Developer',
    url: 'https://careers.apple.com/jobs/3',
    dateApplied: new Date(2024, 2, 28).toISOString(),
    note: 'Passionate about iOS development',
    status: 'Accepted',
    priority: 'high',
    createdAt: new Date(2024, 2, 28).toISOString(),
    updatedAt: new Date(2024, 3, 12).toISOString(),
  },
  {
    id: '4',
    userId: '1',
    company: 'Microsoft',
    position: 'Cloud Solutions Architect',
    url: 'https://careers.microsoft.com/jobs/4',
    dateApplied: new Date(2024, 1, 15).toISOString(),
    note: 'Requires Azure certification',
    status: 'Rejected',
    priority: 'low',
    createdAt: new Date(2024, 1, 15).toISOString(),
    updatedAt: new Date(2024, 2, 5).toISOString(),
  },
  {
    id: '5',
    userId: '1',
    company: 'Amazon',
    position: 'Software Development Engineer',
    url: 'https://careers.amazon.com/jobs/5',
    dateApplied: new Date(2024, 3, 22).toISOString(),
    note: 'Waiting for first round',
    status: 'Applied',
    priority: 'medium',
    createdAt: new Date(2024, 3, 22).toISOString(),
    updatedAt: new Date(2024, 3, 22).toISOString(),
  },
  {
    id: '6',
    userId: '1',
    company: 'Netflix',
    position: 'Full Stack Engineer',
    url: 'https://careers.netflix.com/jobs/6',
    dateApplied: new Date(2024, 3, 20).toISOString(),
    note: 'Interested in streaming platform',
    status: 'Applied',
    priority: 'high',
    createdAt: new Date(2024, 3, 20).toISOString(),
    updatedAt: new Date(2024, 3, 20).toISOString(),
  },
  {
    id: '7',
    userId: '1',
    company: 'Tesla',
    position: 'Autonomous Systems Engineer',
    url: 'https://careers.tesla.com/jobs/7',
    dateApplied: new Date(2024, 2, 5).toISOString(),
    note: 'Self-driving technology fascinates me',
    status: 'Pending',
    priority: 'high',
    createdAt: new Date(2024, 2, 5).toISOString(),
    updatedAt: new Date(2024, 3, 10).toISOString(),
  },
  {
    id: '8',
    userId: '1',
    company: 'OpenAI',
    position: 'Research Scientist',
    url: 'https://careers.openai.com/jobs/8',
    dateApplied: new Date(2024, 3, 1).toISOString(),
    note: 'Interested in AI research',
    status: 'Interview',
    priority: 'high',
    createdAt: new Date(2024, 3, 1).toISOString(),
    updatedAt: new Date(2024, 3, 19).toISOString(),
  },
];
